"""create manuscripts, assets and journal templates

Revision ID: ae12d0a4069f
Revises: d173c614043f
Create Date: 2026-08-14 02:34:10.371804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae12d0a4069f'
down_revision: Union[str, None] = 'd173c614043f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('heading_structure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reference_format', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('formatting_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('title_page_layout', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required_statements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_abstract_words', sa.Integer(), nullable=True),
    sa.Column('max_total_words', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_journal_templates_slug'), 'journal_templates', ['slug'], unique=True)
    op.create_table('template_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('rule_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rule_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rule_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['journal_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_rules_template_id'), 'template_rules', ['template_id'], unique=False)
    op.create_table('manuscripts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_journal_id', sa.Uuid(), nullable=True),
    sa.Column('raw_parsed_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('exported_storage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['target_journal_id'], ['journal_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manuscripts_project_id'), 'manuscripts', ['project_id'], unique=False)
    op.create_table('extracted_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('manuscript_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('affiliations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('corresponding_author', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('abstract', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('funding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conflict_of_interest', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ethics_statement', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_availability', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author_contributions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('acknowledgements', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_human_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_metadata_manuscript_id'), 'extracted_metadata', ['manuscript_id'], unique=True)
    op.create_table('manuscript_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('manuscript_id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('caption', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manuscript_assets_manuscript_id'), 'manuscript_assets', ['manuscript_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manuscript_assets_manuscript_id'), table_name='manuscript_assets')
    op.drop_table('manuscript_assets')
    op.drop_index(op.f('ix_extracted_metadata_manuscript_id'), table_name='extracted_metadata')
    op.drop_table('extracted_metadata')
    op.drop_index(op.f('ix_manuscripts_project_id'), table_name='manuscripts')
    op.drop_table('manuscripts')
    op.drop_index(op.f('ix_template_rules_template_id'), table_name='template_rules')
    op.drop_table('template_rules')
    op.drop_index(op.f('ix_journal_templates_slug'), table_name='journal_templates')
    op.drop_table('journal_templates')
    # ### end Alembic commands ###
